"use strict";
(() => {
  const exact={"alternating floor press":"Distensioni a terra alternate","around the worlds":"Giro del mondo con pesi","barbell bench press - medium grip":"Panca piana con bilanciere, presa media","barbell guillotine bench press":"Distensioni a ghigliottina su panca con bilanciere","barbell incline bench press - medium grip":"Panca inclinata con bilanciere, presa media","bench press - with bands":"Panca piana con elastici","bent-arm dumbbell pullover":"Pullover a braccia flesse con manubrio","bodyweight flyes":"Croci a corpo libero","butterfly":"Croci alla pec deck","cable chest press":"Distensioni per il petto ai cavi","cable crossover":"Croci ai cavi","dumbbell bench press":"Panca piana con manubri","dumbbell floor press":"Distensioni a terra con manubri","dumbbell flyes":"Croci con manubri","barbell curl":"Curl con bilanciere","barbell squat":"Squat con bilanciere","front barbell squat":"Front squat con bilanciere","goblet squat":"Goblet squat","hack squat":"Hack squat","romanian deadlift":"Stacco rumeno","seated cable rows":"Rematore al cavo da seduto","lying leg curls":"Leg curl da sdraiato","seated leg curl":"Leg curl da seduto","side lateral raise":"Alzate laterali in piedi","standing calf raises":"Calf raise in piedi","triceps pushdown":"Pushdown per tricipiti","wide-grip lat pulldown":"Lat machine a presa larga","ab crunch machine":"Crunch alla macchina","ab roller":"Ruota per addominali","air bike":"Crunch bicicletta","bench dips":"Dip su panca","concentration curls":"Curl di concentrazione","dips - chest version":"Dip per il petto","dips - triceps version":"Dip per i tricipiti","incline dumbbell press":"Panca inclinata con manubri"};
  const terms=[["close-grip","presa stretta"],["wide-grip","presa larga"],["medium grip","presa media"],["reverse grip","presa inversa"],["neutral grip","presa neutra"],["alternating","alternato"],["alternate","alternato"],["single-arm","a un braccio"],["one-arm","a un braccio"],["single-leg","a una gamba"],["overhead","sopra la testa"],["incline","inclinato"],["decline","declinato"],["seated","da seduto"],["standing","in piedi"],["kneeling","in ginocchio"],["lying","da sdraiato"],["bent-arm","a braccia flesse"],["bodyweight","a corpo libero"],["with bands","con elastici"],["with chains","con catene"],["smith machine","Smith machine"],["medicine ball","palla medica"],["exercise ball","fitball"],["stability ball","fitball"],["e-z bar","bilanciere EZ"],["ez-bar","bilanciere EZ"],["barbell","bilanciere"],["dumbbells","manubri"],["dumbbell","manubrio"],["kettlebell","kettlebell"],["cable","cavo"],["machine","macchina"],["bench press","distensioni su panca"],["floor press","distensioni a terra"],["chest press","distensioni per il petto"],["shoulder press","distensioni per le spalle"],["leg press","pressa per le gambe"],["push-up","piegamenti"],["pull-up","trazioni"],["chin-up","trazioni supine"],["pulldown","lat machine"],["row","rematore"],["flyes","croci"],["flye","croce"],["lateral raise","alzate laterali"],["front raise","alzate frontali"],["deadlift","stacco"],["lunge","affondo"],["shrug","scrollata"],["stretch","allungamento"],["rotation","rotazione"],["twist","torsione"],["jump","salto"],["throw","lancio"],["raise","sollevamento"],["extension","estensione"],["adduction","adduzione"],["abduction","abduzione"],["chest","petto"],["shoulder","spalla"],["triceps","tricipiti"],["biceps","bicipiti"],["hamstring","femorali"],["quadriceps","quadricipiti"],["glute","gluteo"],["calf","polpaccio"],["forearm","avambraccio"],["wrist","polso"],["neck","collo"],["hip","anca"],["knee","ginocchio"],["ankle","caviglia"],["arm","braccio"],["leg","gamba"],["back","schiena"],["front","frontale"],["side","laterale"],["rear","posteriore"],["reverse","inverso"],["weighted","zavorrato"],["assisted","assistito"]];
  window.translateExerciseName=function(name){const source=name.trim();if(exact[source.toLowerCase()])return exact[source.toLowerCase()];let result=` ${source.toLowerCase()} `;terms.forEach(([a,b])=>{result=result.split(a).join(b)});result=result.replaceAll(" with "," con ").replaceAll(" and "," e ").replaceAll(" of "," di ").replaceAll(" the "," ").replaceAll(" - ",", ").replaceAll("  "," ").trim();return result.charAt(0).toUpperCase()+result.slice(1)};
  const oldCard=createCatalogCard;createCatalogCard=function(exercise){const card=oldCard(exercise);card.querySelector("h3").textContent=translateExerciseName(exercise.name);return card};
  const oldSelection=updateCatalogSelection;updateCatalogSelection=function(){oldSelection();const label=document.querySelector("#catalogSelectedName");if(label&&selectedCatalogExercise)label.textContent=translateExerciseName(selectedCatalogExercise.name)};
  document.querySelector("#confirmCatalogExercise")?.addEventListener("click",()=>{if(selectedCatalogExercise)selectedCatalogExercise.name=translateExerciseName(selectedCatalogExercise.name)},{capture:true});
  window.ITALIAN_NAMES_READY=true;
})();
