"use strict";
(function initializeWorkoutExcelExport(){
if(typeof buildWorkoutDayData!=="function"||!document.querySelector("#workoutExportOverlay")){window.setTimeout(initializeWorkoutExcelExport,30);return}
let exportFormat="markdown";
const XLSX_MIME="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
const columns=[
  {label:"Data",width:13},{label:"Giorno",width:14},{label:"Allenamento",width:20},{label:"Esercizio",width:30},
  {label:"Parte del corpo",width:24},{label:"Programma",width:14},{label:"Serie previste",width:15},{label:"Serie completate",width:17},
  {label:"Numeri serie completate",width:23},{label:"Peso usato (kg)",width:18},{label:"Note",width:42},{label:"Stato",width:13}
];
function xmlEscape(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")}
function excelColumn(index){let result="";for(let value=index+1;value>0;value=Math.floor((value-1)/26))result=String.fromCharCode(65+(value-1)%26)+result;return result}
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}
function zipDateTime(date=new Date()){const year=Math.max(1980,date.getFullYear()),time=(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1),day=((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate();return{time,day}}
function writeUint16(view,offset,value){view.setUint16(offset,value,true)}
function writeUint32(view,offset,value){view.setUint32(offset,value,true)}
function makeZip(files){const encoder=new TextEncoder(),parts=[],central=[],stamp=zipDateTime();let offset=0;Object.entries(files).forEach(([name,content])=>{const nameBytes=encoder.encode(name),data=encoder.encode(content),crc=crc32(data),local=new Uint8Array(30+nameBytes.length),localView=new DataView(local.buffer);writeUint32(localView,0,0x04034b50);writeUint16(localView,4,20);writeUint16(localView,6,0x0800);writeUint16(localView,8,0);writeUint16(localView,10,stamp.time);writeUint16(localView,12,stamp.day);writeUint32(localView,14,crc);writeUint32(localView,18,data.length);writeUint32(localView,22,data.length);writeUint16(localView,26,nameBytes.length);writeUint16(localView,28,0);local.set(nameBytes,30);parts.push(local,data);const header=new Uint8Array(46+nameBytes.length),view=new DataView(header.buffer);writeUint32(view,0,0x02014b50);writeUint16(view,4,20);writeUint16(view,6,20);writeUint16(view,8,0x0800);writeUint16(view,10,0);writeUint16(view,12,stamp.time);writeUint16(view,14,stamp.day);writeUint32(view,16,crc);writeUint32(view,20,data.length);writeUint32(view,24,data.length);writeUint16(view,28,nameBytes.length);writeUint16(view,30,0);writeUint16(view,32,0);writeUint16(view,34,0);writeUint16(view,36,0);writeUint32(view,38,0);writeUint32(view,42,offset);header.set(nameBytes,46);central.push(header);offset+=local.length+data.length});const centralOffset=offset,centralSize=central.reduce((sum,item)=>sum+item.length,0),end=new Uint8Array(22),endView=new DataView(end.buffer);writeUint32(endView,0,0x06054b50);writeUint16(endView,4,0);writeUint16(endView,6,0);writeUint16(endView,8,central.length);writeUint16(endView,10,central.length);writeUint32(endView,12,centralSize);writeUint32(endView,16,centralOffset);writeUint16(endView,20,0);return new Blob([...parts,...central,end],{type:XLSX_MIME})}
function exportDays(){if(currentWorkoutExportMode==="week"){const week=currentWeek();return DAY_ORDER.filter(day=>WORKOUTS[day]).map((day,order)=>({order,data:buildWorkoutDayData(day,workoutDateInWeek(WORKOUTS[day],week))})).sort((a,b)=>a.data.dateValue-b.data.dateValue||a.order-b.order).map(item=>item.data)}return[buildWorkoutDayData(activeDay,new Date())]}
function excelRows(){const rows=[];exportDays().forEach(data=>data.exerciseExports.slice().sort((a,b)=>a.index-b.index).forEach(item=>rows.push([
  data.date.italian,data.workout.weekday,data.workout.title,item.exercise.name,item.exercise.focus||"",item.exercise.setsReps,item.setCount,
  item.doneSetNumbers.length,item.doneSetNumbers.join(", "),item.state.weight||"",item.state.notes?.trim()||"",item.skipped?"Saltato":"Completato"
])));return rows}
function worksheetXml(rows){const allRows=[columns.map(column=>column.label),...rows],sheetRows=allRows.map((row,rowIndex)=>`<row r="${rowIndex+1}"${rowIndex===0?' ht="24" customHeight="1"':""}>${row.map((value,columnIndex)=>{const ref=`${excelColumn(columnIndex)}${rowIndex+1}`,style=rowIndex===0?1:(columnIndex===10?2:0);if(typeof value==="number")return`<c r="${ref}" s="${style}" t="n"><v>${value}</v></c>`;return`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(value)}</t></is></c>`}).join("")}</row>`).join(""),lastColumn=excelColumn(columns.length-1),lastRow=Math.max(1,allRows.length);return`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${columns.map((column,index)=>`<col min="${index+1}" max="${index+1}" width="${column.width}" customWidth="1"/>`).join("")}</cols><sheetData>${sheetRows}</sheetData><autoFilter ref="A1:${lastColumn}${lastRow}"/><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/></worksheet>`}
function buildExcelFile(){const rows=excelRows(),files={
  "[Content_Types].xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`,
  "_rels/.rels":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
  "xl/workbook.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Allenamenti" sheetId="1" r:id="rId1"/></sheets></workbook>`,
  "xl/_rels/workbook.xml.rels":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
  "xl/styles.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FF102019"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF7EE2AD"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normale" xfId="0" builtinId="0"/></cellStyles></styleSheet>`,
  "xl/worksheets/sheet1.xml":worksheetXml(rows)
};const label=currentWorkoutExportMode==="week"?currentWorkoutExport.title:`${exportDateParts().italian} · ${WORKOUTS[activeDay].title}`,filename=currentWorkoutExportMode==="week"?currentWorkoutExport.filename.replace(/\.md$/i,".xlsx"):`${exportDateParts().file}-${exportFilePart(WORKOUTS[activeDay].title)}.xlsx`;return{blob:makeZip(files),filename,title:`Allenamenti · ${label}`,rowCount:rows.length}}
function updateFormatUi(){const overlay=document.querySelector("#workoutExportOverlay"),excel=exportFormat==="excel";overlay.querySelectorAll("[data-export-format]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.exportFormat===exportFormat)));overlay.querySelector(".workout-export-preview").hidden=excel;overlay.querySelector("#copyWorkoutExportButton").hidden=excel;overlay.querySelector("#downloadWorkoutExportButton").textContent=excel?"Scarica .xlsx":"Scarica .md";overlay.querySelector(".workout-export-help").textContent=excel?"Crea un foglio Excel con una riga per esercizio, pronto per filtri, ordinamenti e analisi.":"Condividi il testo Markdown con app di note, email, cloud e altri servizi compatibili, oppure salvalo come file.";setWorkoutExportStatus("")}
async function shareExcel(){const fileData=buildExcelFile(),file=new File([fileData.blob],fileData.filename,{type:XLSX_MIME});if(!navigator.share||!navigator.canShare?.({files:[file]})){setWorkoutExportStatus("La condivisione di file Excel non è disponibile qui: usa Scarica .xlsx.");return}try{await navigator.share({files:[file],title:fileData.title});setWorkoutExportStatus(`File Excel condiviso · ${fileData.rowCount} righe.`,true)}catch(error){if(error?.name!=="AbortError")setWorkoutExportStatus("Condivisione non riuscita. Puoi scaricare il file Excel.")}}
function downloadExcel(){const fileData=buildExcelFile(),url=URL.createObjectURL(fileData.blob),link=document.createElement("a");link.href=url;link.download=fileData.filename;document.body.append(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setWorkoutExportStatus(`File ${fileData.filename} creato · ${fileData.rowCount} righe.`,true)}
function injectExcelUi(){const overlay=document.querySelector("#workoutExportOverlay"),period=overlay.querySelector(".workout-export-mode"),format=document.createElement("div");format.className="workout-export-format";format.setAttribute("role","group");format.setAttribute("aria-label","Formato di esportazione");format.innerHTML='<button type="button" data-export-format="markdown" aria-pressed="true">Markdown</button><button type="button" data-export-format="excel" aria-pressed="false">Excel</button>';period.after(format);format.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{exportFormat=button.dataset.exportFormat;updateFormatUi()}));overlay.querySelectorAll("[data-export-mode]").forEach(button=>button.addEventListener("click",updateFormatUi));overlay.querySelector("#shareWorkoutExportButton").addEventListener("click",event=>{if(exportFormat!=="excel")return;event.stopImmediatePropagation();shareExcel()},true);overlay.querySelector("#downloadWorkoutExportButton").addEventListener("click",event=>{if(exportFormat!=="excel")return;event.stopImmediatePropagation();downloadExcel()},true);const style=document.createElement("style");style.textContent='.workout-export-format{display:grid;grid-template-columns:1fr 1fr;gap:4px;margin:-5px 0 12px;padding:4px;border:1px solid var(--border);border-radius:13px;background:var(--surface-strong)}.workout-export-format button{min-height:37px;border:0;border-radius:9px;background:transparent;color:var(--muted);font-weight:800;cursor:pointer}.workout-export-format button[aria-pressed="true"]{background:rgb(126 226 173 / 16%);color:var(--accent)}';document.head.append(style);updateFormatUi()}
injectExcelUi();
})();
