"use strict";
const WORKOUT_NAMES_STORAGE_KEY="fitness-workout-names-v1";let workoutNames=loadJson(WORKOUT_NAMES_STORAGE_KEY,{});STORAGE_KEYS.workoutNames=WORKOUT_NAMES_STORAGE_KEY;
function applyStoredWorkoutNames(){DAY_ORDER.forEach(day=>{const savedName=String(workoutNames[day]||"").trim();if(savedName)WORKOUTS[day].title=savedName})}
function updateWorkoutNameUi(){elements.workoutTitle.textContent=WORKOUTS[activeDay].title;elements.tabButtons.forEach(button=>{const day=button.dataset.day,weekday=button.querySelector("span")?.textContent||"";button.replaceChildren();const weekdayLabel=document.createElement("span");weekdayLabel.textContent=weekday;button.append(weekdayLabel,document.createTextNode(WORKOUTS[day].title))});document.querySelectorAll("select").forEach(select=>{DAY_ORDER.forEach(day=>{const option=[...select.options].find(item=>item.value===day);if(option)option.textContent=WORKOUTS[day].title})});const input=document.querySelector("#workoutNameInput");if(input&&document.activeElement!==input)input.value=WORKOUTS[activeDay].title}
function saveWorkoutName(){const input=document.querySelector("#workoutNameInput"),nextName=input.value.trim();if(!nextName){input.value=WORKOUTS[activeDay].title;return}workoutNames[activeDay]=nextName;WORKOUTS[activeDay].title=nextName;localStorage.setItem(WORKOUT_NAMES_STORAGE_KEY,JSON.stringify(workoutNames));updateWorkoutNameUi()}
function injectWorkoutNameEditor(){if(document.querySelector("#workoutNameEditor"))return;const editor=document.createElement("label");editor.id="workoutNameEditor";editor.className="workout-name-editor";editor.innerHTML=`<span>Nome allenamento</span><input id="workoutNameInput" type="text" maxlength="40" autocomplete="off" aria-label="Nome allenamento">`;document.querySelector(".workout-heading > div").append(editor);const input=editor.querySelector("input");input.addEventListener("change",saveWorkoutName);input.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();input.blur()}})}
function moveDayActionsToBottom(){let footer=document.querySelector("#workoutDayActions");if(!footer){footer=document.createElement("section");footer.id="workoutDayActions";footer.className="workout-day-actions";footer.setAttribute("aria-label","Azioni giornata");document.querySelector("#lowerRotationNote").after(footer)}const exportButton=document.querySelector("#exportWorkoutButton"),resetButton=document.querySelector("#resetDayButton");if(exportButton&&exportButton.parentElement!==footer){exportButton.className="primary-button";exportButton.textContent="Esporta giornata";footer.append(exportButton)}if(resetButton&&resetButton.parentElement!==footer){resetButton.className="secondary-button danger-outline";footer.append(resetButton)}document.querySelectorAll(".workout-heading-actions").forEach(container=>{if(!container.children.length)container.remove()})}
function simplifyPageHeader(){document.querySelector(".app-header h1").textContent="SCHEDA PALESTRA";document.querySelector(".app-header .eyebrow")?.remove();document.querySelector(".dashboard")?.remove()}
function injectWorkoutLayoutStyles(){const style=document.createElement("style");style.textContent=`.app-header{padding-bottom:12px}.app-header h1{font-size:clamp(1.65rem,7vw,2.25rem);text-transform:none}.quick-notes{margin-top:4px}.workout-heading{align-items:start}.workout-name-editor{display:none;margin-top:13px}.workout-name-editor span{margin-bottom:5px}.workout-name-editor input{width:min(100%,320px);min-height:44px;padding:9px 11px;border:1px solid var(--border);border-radius:11px;background:var(--bg);color:var(--text);font-weight:750}body.is-editing-workout .workout-name-editor{display:block}.workout-day-actions{display:grid;grid-template-columns:1.2fr 1fr;gap:9px;margin:18px 0 34px;padding-top:18px;border-top:1px solid var(--border)}.workout-day-actions button{width:100%}.danger-outline{border-color:rgb(255 142 142 / 38%);color:var(--danger)}@media(max-width:520px){.workout-day-actions{grid-template-columns:1fr}.quick-notes{margin-bottom:15px}}`;document.head.append(style)}
applyStoredWorkoutNames();injectWorkoutNameEditor();simplifyPageHeader();injectWorkoutLayoutStyles();const renderWorkoutBeforeLayout=renderWorkout;renderWorkout=function renderWorkoutWithNames(){renderWorkoutBeforeLayout();updateWorkoutNameUi()};updateWorkoutNameUi();moveDayActionsToBottom();new MutationObserver(()=>moveDayActionsToBottom()).observe(document.body,{childList:true,subtree:true});